### PR TITLE
Allow scrolling a list for large amount of accounts

### PR DESCRIPTION
**Pull request by Tbaut**
The pop-over was not showing all accounts, and didn't allow to scroll.
To test, get a lot of accounts, or try reducing the window height. 
This PR solves that.

image

### CODE REVIEW

**Review by 0xKheops — CHANGES_REQUESTED** [review]
GM fren !

Thank you for picking up this issue !

Tried it and the dropdown is now taking the whole screen height, also the scrollbar appears even if not necessary.
May you please adjust it so it keeps old height behavior and only start scrolling if there isn't enough screen height to display all entries ?

Screenshot taken using Chromium on linux : 
image

**Comment by Tbaut** [comment]
Thanks for the thorough test, I'll fix this today :)

**Comment by Tbaut** [comment]
Should be better now. The overflow-auto will make sure the scrollbar isn't always present when not needed
image

**Review by 0xKheops — APPROVED** [review]
Thanks, LGTM !

**Pull request merged**
